export const mockData = {
  draw: 1,
  data: [
    {
      requestNumber: "25-10-1-0004",
      externalAuthorityName: "النيابة العامة",
      requestTypeName: "أمر تمديد",
      prisonerName: "MD - - SHAHPARAN",
      prisonerNationalId: "3568615128",
      sendDate: "01/10/2025",
      requestStatusName: "قيد التنفيذ",
      requestType: "Extend",
    },
    {
      requestNumber: "25-10-1-0003",
      externalAuthorityName: "النيابة العامة",
      requestTypeName: "استلام",
      prisonerName: "MD - - SHAHPARAN",
      prisonerNationalId: "3568615128",
      sendDate: "01/10/2025",
      requestStatusName: "قيد التنفيذ",
      requestType: "Receiving",
    },
    {
      requestNumber: "25-10-1-0002",
      externalAuthorityName: "النيابة العامة",
      requestTypeName: "أمر تمديد",
      prisonerName: "مشاري خالد محمد الرضيان",
      prisonerNationalId: "1102688916",
      sendDate: "01/10/2025",
      requestStatusName: "قيد التنفيذ",
      requestType: "Extend",
    },
    {
      requestNumber: "25-10-1-0001",
      externalAuthorityName: "النيابة العامة",
      requestTypeName: "أمر تمديد",
      prisonerName: "مشاري خالد محمد الرضيان",
      prisonerNationalId: "1102688916",
      sendDate: "01/10/2025",
      requestStatusName: "قيد التنفيذ",
      requestType: "Extend",
    },
  ],
  recordsTotal: 4,
  recordsFiltered: 4,
};
