export const mockData = {
  draw: 2,
  data: [
    {
      id: 11,
      name: "إطلاق بكفالة",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 1,
      name: "إطلاق سراح",
      parentId: null,
      parentName: null,
    },
    {
      id: 10,
      name: "أمر من النيابة",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 5,
      name: "ابعاد",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 6,
      name: "افراج صحي",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 24,
      name: "انتحار",
      parentId: 3,
      parentName: "وفاه",
    },
    {
      id: 8,
      name: "تنفيذ حكم شرعى",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 13,
      name: "حفظ الدعوى",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 21,
      name: "خارج السجن",
      parentId: 2,
      parentName: "هروب",
    },
    {
      id: 20,
      name: "داخل السجن",
      parentId: 2,
      parentName: "هروب",
    },
    {
      id: 23,
      name: "طبيعية",
      parentId: 3,
      parentName: "وفاه",
    },
    {
      id: 12,
      name: "عدم ادانه",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 22,
      name: "عفو رمضان",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 27,
      name: "عفو شهر و شهرين",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 4,
      name: "عفو ملكى",
      parentId: 1,
      parentName: "إطلاق سراح",
    },
    {
      id: 26,
      name: "مقتول",
      parentId: 3,
      parentName: "وفاه",
    },
    {
      id: 2,
      name: "هروب",
      parentId: null,
      parentName: null,
    },
    {
      id: 3,
      name: "وفاه",
      parentId: null,
      parentName: null,
    },
  ],
  recordsTotal: 18,
  recordsFiltered: 18,
};
