export const mockData = {
  draw: 2,
  data: [
    {
      id: 4,
      name: "اتلاف ما دون النفس",
      parentId: null,
      parentName: null,
    },
    {
      id: 7,
      name: "الإبعاد",
      parentId: null,
      parentName: null,
    },
    {
      id: 11,
      name: "الاكتفاء بما مضى عليه من سجن",
      parentId: null,
      parentName: null,
    },
    {
      id: 3,
      name: "الجلد",
      parentId: null,
      parentName: null,
    },
    {
      id: 6,
      name: "الغرامات",
      parentId: null,
      parentName: null,
    },
    {
      id: 2,
      name: "القصاص",
      parentId: null,
      parentName: null,
    },
    {
      id: 10,
      name: "المبالغ المالية",
      parentId: null,
      parentName: null,
    },
    {
      id: 8,
      name: "المصادرة",
      parentId: null,
      parentName: null,
    },
    {
      id: 12,
      name: "حفظ الاتهام",
      parentId: null,
      parentName: null,
    },
    {
      id: 19,
      name: "رجم",
      parentId: 2,
      parentName: "القصاص",
    },
    {
      id: 1,
      name: "سجن",
      parentId: null,
      parentName: null,
    },
    {
      id: 5,
      name: "عدم الإدانة",
      parentId: null,
      parentName: null,
    },
    {
      id: 13,
      name: "قتل تعزير",
      parentId: 2,
      parentName: "القصاص",
    },
    {
      id: 17,
      name: "قتل حد",
      parentId: 2,
      parentName: "القصاص",
    },
    {
      id: 16,
      name: "قتل حد حرابه",
      parentId: 2,
      parentName: "القصاص",
    },
    {
      id: 14,
      name: "قتل حد غيلة",
      parentId: 2,
      parentName: "القصاص",
    },
    {
      id: 15,
      name: "قتل قصاص",
      parentId: 2,
      parentName: "القصاص",
    },
    {
      id: 18,
      name: "قصاص مؤجل",
      parentId: 2,
      parentName: "القصاص",
    },
    {
      id: 20,
      name: "قطع حد",
      parentId: 4,
      parentName: "اتلاف ما دون النفس",
    },
    {
      id: 23,
      name: "قطع حد الحرابة",
      parentId: 4,
      parentName: "اتلاف ما دون النفس",
    },
    {
      id: 21,
      name: "قطع حد السرقة",
      parentId: 4,
      parentName: "اتلاف ما دون النفس",
    },
    {
      id: 22,
      name: "قطع قصاص",
      parentId: 4,
      parentName: "اتلاف ما دون النفس",
    },
    {
      id: 9,
      name: "منع السفر",
      parentId: null,
      parentName: null,
    },
  ],
  recordsTotal: 23,
  recordsFiltered: 23,
};
