import LayoutWrapper from "@/components/layout/LayoutWrapper";
import { Noto_Sans_Arabic } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

// global font
const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-noto-sans-arabic",
});

export const metadata = {
  title: "Nazeel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
              <Toaster position="top-center" />

        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
