import LayoutWrapper from "@/components/layout/LayoutWrapper";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Nazeel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <Toaster position="top-center" />

        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
