import { Toaster } from "react-hot-toast";
import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";
import Providers from "@/Providers/rq_provider";
import { AuthGuard } from "@/components/AuthGuard";

export const metadata = {
  title: "Nazeel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <Toaster position="top-center" />
        <Providers>
          <AuthProvider>
            <AuthGuard>
              {children}
            </AuthGuard>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
