export const mockData = {
  draw: 2,
  data: [
    {
      id: "80a7467a-b225-42c9-b5f1-c5648abeb28e",
      image: null,
      name: "صالح مطر ثواب العصيمي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1075517720",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "09/04/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "13/04/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-10-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "5b264420-b0ed-420c-b964-40d1066b8587",
      image: null,
      name: "صقر نوح عبدالله الشهري",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1114415670",
      nationality: "العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "08/04/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "11/04/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "9fd33b8e-134a-41e3-94b4-8c5be133f704",
      image: null,
      name: "بداح معجب مبارك الدوسري",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1127598678",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "22/03/1451 - 03/08/2029",
      condemnation:
        "السجن : عدد ٥ سنة و ٠ شهر و ٠ يوم<br>منع السفر: يوم: ٠, شهر: ٠, سنه: ٥<br>الجلد: عدد الدفعات: ١, عدد الجلد لكل دفعة: ٨٠<br>المبالغ المالية: السبب: قضايا جنائية, المبلغ: ٢٠٠٠٠<br>الابعاد: ابعاد<br>الإتلاف: إتلاف مادون النفس: قدم يسار <br>الغرامة: الجهة: jjjj, المبلغ: 5000",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "23/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "27/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "حكم نهائي",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 4,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "3e5ed000-41d9-465f-b3a6-d12fe5f483fb",
      image: null,
      name: "مشاري خالد محمد الرضيان",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1102688916",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "المخدرات - تهريب مواد مخدرة",
      subCaseId: "597B97AD-B52C-4A66-DEB3-08DD2B15F9FE",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "22/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "25/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "35695897-4b16-4efc-b17f-b96fcd89a2e5",
      image: null,
      name: "فيصل فهد علي الشقراوي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1130783911",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "المخدرات - تعاطي",
      subCaseId: "4B6FC12F-25F1-42F1-8765-08DD0DEB178F",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "22/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "10/06/1448",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "e86fe655-f325-4b67-84c4-581e5de37ac7",
      image: null,
      name: "سلطان دميثان بن رمضان العنزي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1054889223",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "المخدرات - اتجار",
      subCaseId: "6AB0C88B-2364-413D-DEB2-08DD2B15F9FE",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "22/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "25/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "d54621bb-97ee-49d0-96d1-5b081a70f9ac",
      image: null,
      name: "ماجد بن مسفر بن مارق العتيبى",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1030182842",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "المخدرات - اتجار",
      subCaseId: "6AB0C88B-2364-413D-DEB2-08DD2B15F9FE",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "22/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "27/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "c2d4f353-0482-4ec0-874d-20c2b7185399",
      image: null,
      name: "طاهر محمود محمد   أرباب",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "2493918391",
      nationality: "باكستان",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "المخدرات - تعاطي",
      subCaseId: "4B6FC12F-25F1-42F1-8765-08DD0DEB178F",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "19/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "21/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "55123755-c490-4abb-b651-964b34ecc1c8",
      image: null,
      name: "عبدالله أنور بن عبدالله الغامدي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1092580339",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "المخدرات - تعاطي",
      subCaseId: "4B6FC12F-25F1-42F1-8765-08DD0DEB178F",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "16/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "18/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "dfbe8b0d-739e-4429-8faf-911d40ba0812",
      image: null,
      name: "سلطان بن حسين بن علي العنزي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1004296602",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع الاول-الوحدة الاول-الجناح الاول",
      tasksStatus: null,
      prisonId: "8ae0226b-2c9a-424f-ff44-08dafdd87091",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "15/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "19/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "إدارة سجن محافظة الدوادمي",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "603011f7-f06f-4b86-a5d4-067bc0b5cc28",
      image: null,
      name: "ناصر سعد مهدي العتيبي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1106040957",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع الثاني-الوحدة الاول-الجناح الاول",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "15/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "19/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "70ea08d0-195e-46f7-80d1-a38ede89369d",
      image: null,
      name: "سعيدان عزيز مبارك العتيبي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1127479705",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "15/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "19/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "078af37f-64a2-4ced-a97d-c4e62b4868d0",
      image: null,
      name: "الحميدي مبارك الحميدي العتيبي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1063479982",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع السادس-الوحدة الثاني-الجناح الثاني",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "15/03/1452 - 16/07/2030",
      condemnation:
        "منع السفر: يوم: ٠, شهر: ٠, سنه: ٥<br>الغرامة: الجهة: للللللليب, المبلغ: 5000<br>السجن : عدد ٥ سنة و ٠ شهر و ٠ يوم",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "15/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "19/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "حكم نهائي",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 4,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "615a0c5d-d967-4b3e-aa92-a4ae3d77d04d",
      image: null,
      name: "ماجد ثوينى بن براز العتيبى",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1073573428",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع الثاني-الوحدة الاول-الجناح الاول",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "15/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "19/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "be964aff-55a5-4616-947e-c44fbad61420",
      image: null,
      name: "عبدالله حامد اسحيم البيشي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1131536995",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "مجمع رقم 1-وحدة رقم 1-جناح رقم 1",
      tasksStatus: null,
      prisonId: "90f0ccc9-25ac-4182-55aa-08dd0eb28331",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "15/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "20/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "GGGGG",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "ec34d2fc-bb66-4416-b107-610161b77cfc",
      image: null,
      name: "طارق فهد محمد الحمودي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1036436093",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع الثاني-الوحدة الاول-الجناح الاول",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "15/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "19/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "d601bc99-e1c5-4622-a7ce-3f8c38dc55de",
      image: null,
      name: "مهند عثمان بن علي السناني",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1078088075",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "مجمع رقم 1-وحدة رقم 1-جناح رقم 1",
      tasksStatus: null,
      prisonId: "90f0ccc9-25ac-4182-55aa-08dd0eb28331",
      expectedExitDate: "20/06/1447 - 11/12/2025",
      condemnation: "السجن : عدد ٠ سنة و ٣ شهر و ٨ يوم",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "12/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "16/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "حكم نهائي",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 4,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "GGGGG",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "00467703-9534-42b4-80ec-1d59e953bd48",
      image: null,
      name: "ناشى شلال مفرس البقمي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1102145024",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-الجناح  الأول",
      tasksStatus: null,
      prisonId: "8ae0226b-2c9a-424f-ff44-08dafdd87091",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "12/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "16/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "إدارة سجن محافظة الدوادمي",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "cd4bf59c-98f0-49a0-9995-7fc62b3f294b",
      image: null,
      name: "امير شهزاد  أورنجزيب",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "2593082148",
      nationality: "باكستان",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "المخدرات - تعاطي",
      subCaseId: "4B6FC12F-25F1-42F1-8765-08DD0DEB178F",
      accoumdationName: null,
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "12/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "16/04/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: "خارج السجن  ",
      healthStatusName: null,
      prisonerType: 6,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "33820bc7-b0e6-4440-99de-e06e83b1899c",
      image: null,
      name: "رائد محمد بن سعيد الشهري",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1098471921",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "12/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "16/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "ff15e764-2b33-44ed-bfa7-e2d6d84783f8",
      image: null,
      name: "احمد محمد ابراهيم عسيري",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1085354403",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع السادس-الوحدة الثاني-الجناح الثاني",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "12/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "16/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "87b54b30-e457-412e-8239-28148c26dac1",
      image: null,
      name: "ابراهيم منصور عبدالرحمن السران",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1124441831",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "11/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "15/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "موقوف",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 2,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "3c0c4775-18f7-4583-bbc7-f0e5071f2781",
      image: null,
      name: "طلال خالد محمد العتيبي",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1082850270",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "-",
      condemnation: "المبالغ المالية: السبب: قضايا جنائية, المبلغ: ٢٣٢٤",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "11/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "15/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "حكم نهائي",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 4,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "f790a5eb-2586-4fa8-a7c8-03c9a6f6513c",
      image: null,
      name: "عبدالهادي سيف عبدالهادي الدوسري",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1126204450",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "قصاص",
      condemnation: "القصاص: قصاص",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "11/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "15/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "حكم ابتدائي",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 1,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
    {
      id: "ff33b958-db8e-4c8f-98ba-afdc11ddd584",
      image: null,
      name: "سعود يحي محمد حداد",
      nameAr: null,
      nameEn: null,
      birthDate: null,
      birthPlace: null,
      number: null,
      nationalId: "1064628306",
      nationality: "المملكة العربية السعودية",
      nickName: null,
      identityIssuer: null,
      identityEndDate: null,
      educationLevel: null,
      gender: null,
      religion: null,
      socialStatus: null,
      nationalityType: null,
      job: null,
      caseName: "جرائم الخازن - إخلال الخازن القضائي أو تابعه بالتعدي",
      subCaseId: "D4CAF302-C725-4F98-122C-08DDDD5C4632",
      accoumdationName: "المجمع  الأول-الوحدة  الأولى-جناح 123456",
      tasksStatus: null,
      prisonId: "4ddede74-4356-4007-56a1-08dd0defa300",
      expectedExitDate: "09/03/1453 - 29/06/2031",
      condemnation: "السجن : عدد ٣ سنة و ٠ شهر و ٠ يوم<br>القصاص: قصاص",
      address: null,
      incomeAmount: null,
      incomeSource: null,
      prisonEntryDate: "09/03/1447",
      termOfTheSentence: null,
      releaseDateFromPrison: "13/03/1447",
      familyHomeMembershipNO: null,
      identityType: null,
      prisonerTypeName: " داخل السجن",
      healthStatusName: null,
      prisonerType: 1,
      arrestIssuer: null,
      arrestOrder: null,
      healthStatus: 0,
      healthStatusType: null,
      sentenceInPrison: null,
      solitaryConfinement: null,
      housingPlace: null,
      isAnotherCases: null,
      prisonerId: null,
      pardonId: null,
      prisonerStatusName: "حكم ابتدائي",
      prisonerPardoningId: null,
      pardoningTypeId: null,
      prisonerStatus: 1,
      pardoningTypeName: null,
      prisonerTransactionId: null,
      arrestWarranties: null,
      prisonerNumber: "600-25-9-00002",
      familyMembers: [],
      prisonManagerName: null,
      checkIsReleased: null,
      subCase: null,
      visitPrivilege: null,
      callPrivilege: null,
      healthStatusSecurityManager: null,
      caseOfficeRequestId: null,
      prisonName: "الإدارة العامة لسجن الملز",
      quranPartCount: null,
      canViewDetails: true,
    },
  ],
  recordsTotal: 57,
  recordsFiltered: 57,
};
